overrides:
  '@wpmvc/components': link:C:/Users/tanji/AppData/Local/pnpm/global/5/node_modules/@wpmvc/components
  components: link:C:/Users/tanji/AppData/Local/pnpm/global/5/node_modules/@wpmvc/components
